// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StartPagePlus
{
    internal sealed partial class Vsix
    {
        public const string Id = "96b389fd-48b6-48d9-bbf2-ec6ebd026b14";
        public const string Name = "Start Page+";
        public const string Description = @"Bring back Start Page! (a document tab, NOT a modal window)";
        public const string Language = "en-US";
        public const string Version = "2.0.0.3";
        public const string Author = "Yann Duran";
        public const string Tags = "Start Page+, start-page-plus, StartPagePlus, 64 bit, 64bit, start page, start-page, startpage, luminous, yannduran, yd";
    }
}
