// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StartPagePlus
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string StartPagePlusString = "6b4431b4-7dc5-40c7-bf16-8d7ebe2c4608";
        public static Guid StartPagePlus = new Guid(StartPagePlusString);

        public const string StartPagePlusWindowString = "e3be6dd3-f017-4d6e-ae88-2b29319a77a2";
        public static Guid StartPagePlusWindow = new Guid(StartPagePlusWindowString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ViewWindow = 0x0210;
    }
}
